apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: my-app
  name: full-stack-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: full-stack-backend
  template:
    metadata:
      labels:
        app: full-stack-backend
    spec:
      containers:
      - name: full-stack-backend
        image: full-stack/backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
