apiVersion: v1
kind: Service
metadata:
  namespace: my-app
  name: full-stack-backend
spec:
  type: ClusterIP
  selector:
    app: full-stack-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001