apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-stack-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: full-stack-frontend
  template:
    metadata:
      labels:
        app: full-stack-frontend
    spec:
      containers:
      - name: full-stack-frontend
        image: full-stack/frontend:v3
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: full-stack-frontend
spec:
  type: NodePort
  selector:
    app: full-stack-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
