apiVersion: v1
kind: Service
metadata:
  name: full-stack-frontend
  namespace: my-app
spec:
  type: NodePort
  selector:
    app: full-stack-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80