apiVersion: v1
kind: Service
metadata:
  namespace: my-app
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP 
      port: 5432
      targetPort: 5432
  type: ClusterIP
